name: bcdataenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - click>=8.0
  - pip
  - gdal
  - requests
  - owslib
  - rasterio
  - geopandas
  - psycopg2
  - sqlalchemy<2.0
  - geoalchemy2
