name: bcdataenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=21.0.*
  - gdal=3.1.*
  - requests=2.25.*
  - owslib=0.23.*
  - rasterio=1.2.*
  - geopandas=0.9.*
  - psycopg2=2.8.*

